### ISSUE TITLE
Improve documentation notebooks

### ISSUE THREAD

**Issue by malmans2** [MaceKuailv/seaduck#13]
Next thing I suggest you to think about is the notebook you want to show in the documentation.
Ideally, you want to have notebooks that run very quick and can be executed on any machine.
If you are able to do it, we will then do the following:
1. Add a pre-commit hook that strips all output from the notebooks and lint them. Notebook outputs are usually very heavy and we don't want to use version control on that.
2. Add a GitHub action that execute the notebooks, build the documentation, and deploys the documentation (e.g., we can use GitHub pages)

I can help you out with the pre-commit hook and GitHub actions.

If you want to include some advanced code (e.g., code that needs SciServer access), I suggest to use a separate repository for those notebooks. If we are not able to run the notebook with the CI actions, you'll find out soon that it's a nightmare to keep the documentation in sync with the code.

You can use tools like pooch in the documentation notebook as well. Try to avoid comments like `uncomment this if ...`.
I know I know... we probably do that a lot in OceanSpy notebooks... :)

**Comment by MaceKuailv** [comment]
Thanks a lot for the suggestions!

I haven't got enough time to work on the notebooks yet. The current ones was originally part of Tom's notebook suite that runs on sciserver. By default, jupyter book will execute the notebooks automatically. However, because the data I used for those notebooks are all on sciserver, I manually ask it not to run with `execute_notebooks: 'off'` in `docs/-config`. Is that what you meant by the github action?

There is an option in jupyter book to have a markdown notebook, which is essentially something that looks like jupyter notebook but is actually a non-executable thing. At the end of the day, we still need to store the plots and other things as well. However, in that case, those files are not changing, Do you think that will be acceptable for git? 

There is only a few functionalities in my package that does not require a dataset. I think I could have some tutorial examples that does not require a large datasets or could use a generated dataset. But to generate pretty pictures, it almost always need more time and larger data. This is something I really don't want to give up on. I think what I could do is generate a markdown notebook (I don't know how easy it is to do so) that include a instruction on how to register sciserver, and where to download the excutable notebook, which can be stored in other directories. 

I am afraid I am not entirely sure I understand this paragraph here. My understanding is that: when some code changed, the output of notebooks will change, but if notebooks are not executable, it will lag behind. Is that what you meant? However, I think the output should always be the same even if the package changes but still pass all the tests. 
**"If you want to include some advanced code (e.g., code that needs SciServer access), I suggest to use a separate repository for those notebooks. If we are not able to run the notebook with the CI actions, you'll find out soon that it's a nightmare to keep the documentation in sync with the code."** 

What do you think? Am I understanding you correctly?

**Comment by malmans2** [comment]
The problem of running with `execute_notebooks: 'off'` is that if changes to the code (or even upstream libraries) break the notebooks or return different results, you won't even notice it and the notebooks are not in sync with the code.

Ideally you would do this:
1. Design some notebook that quickly runs on any machine. These notebook are executed by the CI. If we use readthedocs, we never need to store the outputs. If we use GH pages, we could execute only when branches are merged into main, and store the output on a separate branch that is deployed on gh-pages.
2. Store complex notebooks (long run time or need sciserver) in a separate repository. In the documentation you can just show the link to that repo/jupyter-book making it clear that those notebooks are not executed frequently and need access to SciServer

**Comment by MaceKuailv** [comment]
That's indeed very nice. I guess my question is how those semi-dormant notebooks can still be build into the documentation? 

For example, I have this notebook (https://github.com/hainegroup/shared-notebooks/blob/main/Archive/picture_book.ipynb) that takes hours to run, but produce very nice pictures that I would love the internet to see:). It is less of a tutorial more of a gallery type of thing. I could definitely add "this notebook was last run on so-and-so-date". But I do want to demonstrate that the package is scalable and can do things with a relatively good performance. So what do you think about the markdown notebook thing? Or do you have better ideas to incorporate them into the documentation?

**Comment by MaceKuailv** [comment]
Things suggested here are all implemented, although the documentation certainly needs more improvement.
