### ISSUE TITLE
Warnings in tests

### ISSUE THREAD

**Issue by MaceKuailv** [MaceKuailv/seaduck#22]
Sometimes there is devide by zero warnings in the tests, which is as intended. I will take a closer look at all of them and silence them with care.

**Comment by MaceKuailv** [comment]
@malmans2 If the code is running correctly, there should be divide by zero warnings from place to place. Do you think it is acceptable to silence all of them in the tests?

**Comment by malmans2** [comment]
I would avoid it. You have a few of that warnings, but they are not that many.
Use [assert](https://docs.pytest.org/en/7.1.x/how-to/capture-warnings.html#warns) as much as possible for warnings that you fully understand, filter the other warnings but not globally (e.g., use the [decorator](https://docs.pytest.org/en/7.1.x/how-to/capture-warnings.html#pytest-mark-filterwarnings)).

Assert is better because if you expect the warning but it won't show up in the future, you know that something is not right. And if you'll get the zero division warning in a function where you don't expect it, you'll notice right away.

**Comment by MaceKuailv** [comment]
close with #58
