### ISSUE TITLE
Output times are uneven

### ISSUE THREAD

**Issue by ThomasHaine** [MaceKuailv/seaduck#6]
How are the output times for Lagrangian particles selected. `stops` are unevenly spaced in:

```
stops,[S,lats,lons,heights] = oi.OceInterp(od._ds,
                                 ['SALT','__particle.lat','__particle.lon','__particle.dep'],
                                 x,y,z,t,
                                 lagrangian = True
                                    )
```
although `t` are evenly spaced. How does the user get output at times `t`?  What are the `stops` times?

**Comment by MaceKuailv** [comment]
This is because the time you set for output does not match that of the output steps (timestep's end). The particle needs to stop at those times anyway, so by default, the return will include those steps. You can set `return_in_between = False` to make those steps go away.

**Comment by ThomasHaine** [comment]
This doesn't seem to be working right:
![image](https://user-images.githubusercontent.com/44037162/203564120-15b8531c-bb8e-4605-8ecb-b6b0b16e8e43.png)

**Comment by MaceKuailv** [comment]
This is as expected. There are two steps in this process. The first step is to make the trajectory, which is what you are seeing now. It just have to stop at the update steps or else it would be wrong. The second step is to select the returns and do the interpolation for other variables, that's where we throughout the update steps. You can take a look at the stops returned after this is done. It should be the same as the input t. Otherwise, there might be a bug some where

**Comment by ThomasHaine** [comment]
OK, but `np.size(lons,0)` = `np.size(t,0) - 1`, which is confusing.

**Comment by MaceKuailv** [comment]
This is more of a issue with documentation than anything else.
